/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Department = IDL.Variant({
  'construction' : IDL.Null,
  'marketing' : IDL.Null,
  'accounts' : IDL.Null,
  'travelDesk' : IDL.Null,
  'apartments' : IDL.Null,
});
export const Time = IDL.Int;
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserSummary = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'department' : IDL.Text,
});
export const TaskStatus = IDL.Variant({
  'red' : IDL.Null,
  'blue' : IDL.Null,
  'green' : IDL.Null,
  'yellow' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ApprovalStatus = IDL.Variant({
  'pendingReview' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const TaskResponse = IDL.Record({
  'status' : TaskStatus,
  'title' : IDL.Text,
  'proofFile' : IDL.Opt(ExternalBlob),
  'assignedTo' : IDL.Principal,
  'completionTime' : IDL.Opt(Time),
  'submissionTimestamp' : IDL.Opt(Time),
  'rejectionReason' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'performancePoints' : IDL.Int,
  'deadline' : Time,
  'approvalStatus' : ApprovalStatus,
  'taskId' : IDL.Nat,
  'proofSubmittedBy' : IDL.Opt(IDL.Text),
  'priority' : TaskPriority,
  'proofSubmittedByEmail' : IDL.Opt(IDL.Text),
  'department' : Department,
});
export const AccountStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'employee' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'accountStatus' : AccountStatus,
  'name' : IDL.Text,
  'role' : UserRole,
  'performancePoints' : IDL.Int,
  'email' : IDL.Text,
  'department' : IDL.Text,
});
export const UserStats = IDL.Record({
  'totalTasks' : IDL.Nat,
  'tasksCompleted' : IDL.Nat,
  'performancePoints' : IDL.Int,
  'profile' : UserProfile,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveTask' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createTask' : IDL.Func(
      [IDL.Text, Department, IDL.Text, IDL.Text, Time, TaskPriority],
      [IDL.Nat],
      [],
    ),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getActiveUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
  'getAdminDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalTasks' : IDL.Nat,
          'completedTasks' : IDL.Nat,
          'leaderboard' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int)),
          'lateTasks' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllTasks' : IDL.Func([], [IDL.Vec(TaskResponse)], ['query']),
  'getAllUsersStats' : IDL.Func([], [IDL.Vec(UserStats)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getTasksForCaller' : IDL.Func([], [IDL.Vec(TaskResponse)], ['query']),
  'getTasksForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TaskResponse)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectTask' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleUserAccountStatus' : IDL.Func([IDL.Principal, AccountStatus], [], []),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'uploadProofFile' : IDL.Func(
      [IDL.Nat, ExternalBlob, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Department = IDL.Variant({
    'construction' : IDL.Null,
    'marketing' : IDL.Null,
    'accounts' : IDL.Null,
    'travelDesk' : IDL.Null,
    'apartments' : IDL.Null,
  });
  const Time = IDL.Int;
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserSummary = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  const TaskStatus = IDL.Variant({
    'red' : IDL.Null,
    'blue' : IDL.Null,
    'green' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ApprovalStatus = IDL.Variant({
    'pendingReview' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const TaskResponse = IDL.Record({
    'status' : TaskStatus,
    'title' : IDL.Text,
    'proofFile' : IDL.Opt(ExternalBlob),
    'assignedTo' : IDL.Principal,
    'completionTime' : IDL.Opt(Time),
    'submissionTimestamp' : IDL.Opt(Time),
    'rejectionReason' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'performancePoints' : IDL.Int,
    'deadline' : Time,
    'approvalStatus' : ApprovalStatus,
    'taskId' : IDL.Nat,
    'proofSubmittedBy' : IDL.Opt(IDL.Text),
    'priority' : TaskPriority,
    'proofSubmittedByEmail' : IDL.Opt(IDL.Text),
    'department' : Department,
  });
  const AccountStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'employee' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'accountStatus' : AccountStatus,
    'name' : IDL.Text,
    'role' : UserRole,
    'performancePoints' : IDL.Int,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  const UserStats = IDL.Record({
    'totalTasks' : IDL.Nat,
    'tasksCompleted' : IDL.Nat,
    'performancePoints' : IDL.Int,
    'profile' : UserProfile,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveTask' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createTask' : IDL.Func(
        [IDL.Text, Department, IDL.Text, IDL.Text, Time, TaskPriority],
        [IDL.Nat],
        [],
      ),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getActiveUsers' : IDL.Func([], [IDL.Vec(UserSummary)], ['query']),
    'getAdminDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalTasks' : IDL.Nat,
            'completedTasks' : IDL.Nat,
            'leaderboard' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int)),
            'lateTasks' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllTasks' : IDL.Func([], [IDL.Vec(TaskResponse)], ['query']),
    'getAllUsersStats' : IDL.Func([], [IDL.Vec(UserStats)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getTasksForCaller' : IDL.Func([], [IDL.Vec(TaskResponse)], ['query']),
    'getTasksForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TaskResponse)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectTask' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleUserAccountStatus' : IDL.Func(
        [IDL.Principal, AccountStatus],
        [],
        [],
      ),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'uploadProofFile' : IDL.Func(
        [IDL.Nat, ExternalBlob, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };