/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountStatus = { 'active' : null } |
  { 'inactive' : null };
export type ApprovalStatus = { 'pendingReview' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Department = { 'construction' : null } |
  { 'marketing' : null } |
  { 'accounts' : null } |
  { 'travelDesk' : null } |
  { 'apartments' : null };
export type ExternalBlob = Uint8Array;
export type FinalStatus = { 'pendingReview' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface TaskResponse {
  'status' : TaskStatus,
  'title' : string,
  'proofFile' : [] | [ExternalBlob],
  'assignedTo' : Principal,
  'completionTime' : [] | [Time],
  'submissionTimestamp' : [] | [Time],
  'finalStatus' : [] | [FinalStatus],
  'rejectionReason' : [] | [string],
  'submittedAt' : [] | [Time],
  'description' : string,
  'performancePoints' : bigint,
  'reviewComment' : [] | [string],
  'deadline' : Time,
  'reviewedAt' : [] | [Time],
  'approvalStatus' : ApprovalStatus,
  'taskId' : bigint,
  'proofSubmittedBy' : [] | [string],
  'priority' : TaskPriority,
  'proofSubmittedByEmail' : [] | [string],
  'department' : Department,
}
export type TaskStatus = { 'red' : null } |
  { 'blue' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export type Time = bigint;
export interface UserProfile {
  'accountStatus' : AccountStatus,
  'name' : string,
  'role' : UserRole,
  'performancePoints' : bigint,
  'email' : string,
  'department' : string,
}
export type UserRole = { 'manager' : null } |
  { 'admin' : null } |
  { 'employee' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'totalTasks' : bigint,
  'tasksCompleted' : bigint,
  'performancePoints' : bigint,
  'profile' : UserProfile,
}
export interface UserSummary {
  'principal' : Principal,
  'name' : string,
  'email' : string,
  'department' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Admin review of a task: approve or reject.
   * / Only admins may call this function.
   * / Rejection requires a non-empty reviewComment.
   */
  'adminReviewTask' : ActorMethod<
    [bigint, FinalStatus, [] | [string]],
    TaskResponse
  >,
  /**
   * / Approve a task. Accessible by admins and managers only.
   */
  'approveTask' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  /**
   * / Create a task. Accessible by admins and managers only.
   * / Accepts an email address as the assignee identifier.
   */
  'createTask' : ActorMethod<
    [string, Department, string, string, Time, TaskPriority],
    bigint
  >,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  /**
   * / Returns all active users (name, email, department, principal).
   * / Accessible by admins and managers only.
   */
  'getActiveUsers' : ActorMethod<[], Array<UserSummary>>,
  /**
   * / Admin dashboard: aggregate statistics.
   */
  'getAdminDashboard' : ActorMethod<
    [],
    {
      'totalTasks' : bigint,
      'completedTasks' : bigint,
      'leaderboard' : Array<[Principal, bigint]>,
      'lateTasks' : bigint,
    }
  >,
  /**
   * / Get all tasks. Accessible by admins and managers only.
   * / Proof fields are included because only admins/managers can call this.
   */
  'getAllTasks' : ActorMethod<[], Array<TaskResponse>>,
  'getAllUsersStats' : ActorMethod<[], Array<UserStats>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  /**
   * / Get tasks assigned to the caller.
   * / Proof fields are visible because the caller is the assigned employee.
   */
  'getTasksForCaller' : ActorMethod<[], Array<TaskResponse>>,
  /**
   * / Get tasks for a specific user.
   * / Admins/managers can view any user's tasks with full proof data.
   * / An employee can only view their own tasks (with proof data).
   * / No other caller may access this endpoint.
   */
  'getTasksForUser' : ActorMethod<[Principal], Array<TaskResponse>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Mark a task as complete (employee's final confirmation after proof upload).
   * / Only the assigned employee (caller == assignedTo) may call this.
   * / The caller must also be a registered user (#user permission).
   * / The task must already have a proofFile uploaded.
   */
  'markComplete' : ActorMethod<[bigint], TaskResponse>,
  /**
   * / Reject a task. Accessible by admins and managers only.
   */
  'rejectTask' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleUserAccountStatus' : ActorMethod<
    [Principal, AccountStatus],
    undefined
  >,
  'updateUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Upload proof for a task.
   * / Only the assigned employee (caller == assignedTo) may call this.
   * / The caller must also be a registered user (#user permission).
   */
  'uploadProof' : ActorMethod<[bigint, ExternalBlob], TaskResponse>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];