/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountStatus = { 'active' : null } |
  { 'inactive' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Department = { 'construction' : null } |
  { 'marketing' : null } |
  { 'accounts' : null } |
  { 'travelDesk' : null } |
  { 'apartments' : null };
export type ExternalBlob = Uint8Array;
export interface Task {
  'status' : TaskStatus,
  'title' : string,
  'proofFile' : [] | [ExternalBlob],
  'assignedTo' : Principal,
  'completionTime' : [] | [Time],
  'rejectionReason' : [] | [string],
  'description' : string,
  'performancePoints' : bigint,
  'deadline' : Time,
  'approvalStatus' : ApprovalStatus,
  'taskId' : bigint,
  'priority' : TaskPriority,
  'department' : Department,
}
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type TaskStatus = { 'red' : null } |
  { 'blue' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export type Time = bigint;
export interface UserProfile {
  'accountStatus' : AccountStatus,
  'name' : string,
  'role' : UserRole,
  'performancePoints' : bigint,
  'department' : string,
}
export type UserRole = { 'manager' : null } |
  { 'admin' : null } |
  { 'employee' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'totalTasks' : bigint,
  'tasksCompleted' : bigint,
  'performancePoints' : bigint,
  'profile' : UserProfile,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Approve a task. Admin-only (admins represent managers in this system).
   */
  'approveTask' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  /**
   * / Create a task. Admin-only (admins represent managers in this system).
   */
  'createTask' : ActorMethod<
    [string, Department, Principal, string, Time, TaskPriority],
    bigint
  >,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  /**
   * / Admin dashboard: aggregate statistics.
   */
  'getAdminDashboard' : ActorMethod<
    [],
    {
      'totalTasks' : bigint,
      'completedTasks' : bigint,
      'leaderboard' : Array<[Principal, bigint]>,
      'lateTasks' : bigint,
    }
  >,
  'getAllUsersStats' : ActorMethod<[], Array<UserStats>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  /**
   * / Get tasks assigned to the caller. Requires at least a registered user.
   */
  'getTasksForCaller' : ActorMethod<[], Array<Task>>,
  /**
   * / Get tasks for a specific user.
   * / Admins can query any user; a regular user can only query their own tasks.
   */
  'getTasksForUser' : ActorMethod<[Principal], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Reject a task. Admin-only (admins represent managers in this system).
   */
  'rejectTask' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleUserAccountStatus' : ActorMethod<
    [Principal, AccountStatus],
    undefined
  >,
  'updateUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Upload proof for a task. Only the assigned employee.
   */
  'uploadProofFile' : ActorMethod<[bigint, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];