/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TaskResponse {
    status: TaskStatus;
    title: string;
    proofFile?: ExternalBlob;
    assignedTo: Principal;
    completionTime?: Time;
    submissionTimestamp?: Time;
    finalStatus?: FinalStatus;
    rejectionReason?: string;
    submittedAt?: Time;
    description: string;
    performancePoints: bigint;
    reviewComment?: string;
    deadline: Time;
    reviewedAt?: Time;
    approvalStatus: ApprovalStatus;
    taskId: bigint;
    proofSubmittedBy?: string;
    priority: TaskPriority;
    proofSubmittedByEmail?: string;
    department: Department;
}
export interface UserSummary {
    principal: Principal;
    name: string;
    email: string;
    department: string;
}
export interface UserProfile {
    accountStatus: AccountStatus;
    name: string;
    role: UserRole;
    performancePoints: bigint;
    email: string;
    department: string;
}
export interface UserStats {
    totalTasks: bigint;
    tasksCompleted: bigint;
    performancePoints: bigint;
    profile: UserProfile;
}
export enum AccountStatus {
    active = "active",
    inactive = "inactive"
}
export enum ApprovalStatus {
    pendingReview = "pendingReview",
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Department {
    construction = "construction",
    marketing = "marketing",
    accounts = "accounts",
    travelDesk = "travelDesk",
    apartments = "apartments"
}
export enum FinalStatus {
    pendingReview = "pendingReview",
    approved = "approved",
    rejected = "rejected"
}
export enum TaskPriority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum TaskStatus {
    red = "red",
    blue = "blue",
    green = "green",
    yellow = "yellow"
}
export enum UserRole {
    manager = "manager",
    admin = "admin",
    employee = "employee"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / Admin review of a task: approve or reject.
     * / Only admins may call this function.
     * / Rejection requires a non-empty reviewComment.
     */
    adminReviewTask(taskId: bigint, decision: FinalStatus, reviewComment: string | null): Promise<TaskResponse>;
    /**
     * / Approve a task. Accessible by admins and managers only.
     */
    approveTask(taskId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    /**
     * / Create a task. Accessible by admins and managers only.
     * / Accepts an email address as the assignee identifier.
     */
    createTask(title: string, department: Department, assigneeEmail: string, description: string, deadline: Time, priority: TaskPriority): Promise<bigint>;
    deleteUser(user: Principal): Promise<void>;
    /**
     * / Returns all active users (name, email, department, principal).
     * / Accessible by admins and managers only.
     */
    getActiveUsers(): Promise<Array<UserSummary>>;
    /**
     * / Admin dashboard: aggregate statistics.
     */
    getAdminDashboard(): Promise<{
        totalTasks: bigint;
        completedTasks: bigint;
        leaderboard: Array<[Principal, bigint]>;
        lateTasks: bigint;
    }>;
    /**
     * / Get all tasks. Accessible by admins and managers only.
     * / Proof fields are included because only admins/managers can call this.
     */
    getAllTasks(): Promise<Array<TaskResponse>>;
    getAllUsersStats(): Promise<Array<UserStats>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    /**
     * / Get tasks assigned to the caller.
     * / Proof fields are visible because the caller is the assigned employee.
     */
    getTasksForCaller(): Promise<Array<TaskResponse>>;
    /**
     * / Get tasks for a specific user.
     * / Admins/managers can view any user's tasks with full proof data.
     * / An employee can only view their own tasks (with proof data).
     * / No other caller may access this endpoint.
     */
    getTasksForUser(user: Principal): Promise<Array<TaskResponse>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Mark a task as complete (employee's final confirmation after proof upload).
     * / Only the assigned employee (caller == assignedTo) may call this.
     * / The caller must also be a registered user (#user permission).
     * / The task must already have a proofFile uploaded.
     */
    markComplete(taskId: bigint): Promise<TaskResponse>;
    /**
     * / Reject a task. Accessible by admins and managers only.
     */
    rejectTask(taskId: bigint, reason: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleUserAccountStatus(user: Principal, status: AccountStatus): Promise<void>;
    updateUserRole(user: Principal, newRole: UserRole): Promise<void>;
    /**
     * / Upload proof for a task.
     * / Only the assigned employee (caller == assignedTo) may call this.
     * / The caller must also be a registered user (#user permission).
     */
    uploadProof(taskId: bigint, file: ExternalBlob): Promise<TaskResponse>;
}
import type { AccountStatus as _AccountStatus, ApprovalStatus as _ApprovalStatus, Department as _Department, ExternalBlob as _ExternalBlob, FinalStatus as _FinalStatus, TaskPriority as _TaskPriority, TaskResponse as _TaskResponse, TaskStatus as _TaskStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, UserStats as _UserStats, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminReviewTask(arg0: bigint, arg1: FinalStatus, arg2: string | null): Promise<TaskResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.adminReviewTask(arg0, to_candid_FinalStatus_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return from_candid_TaskResponse_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminReviewTask(arg0, to_candid_FinalStatus_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return from_candid_TaskResponse_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTask(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTask(arg0: string, arg1: Department, arg2: string, arg3: string, arg4: Time, arg5: TaskPriority): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, to_candid_Department_n30(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_TaskPriority_n32(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, to_candid_Department_n30(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_TaskPriority_n32(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getActiveUsers(): Promise<Array<UserSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveUsers();
            return result;
        }
    }
    async getAdminDashboard(): Promise<{
        totalTasks: bigint;
        completedTasks: bigint;
        leaderboard: Array<[Principal, bigint]>;
        lateTasks: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminDashboard();
            return result;
        }
    }
    async getAllTasks(): Promise<Array<TaskResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsersStats(): Promise<Array<UserStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersStats();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersStats();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksForCaller(): Promise<Array<TaskResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksForCaller();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksForCaller();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksForUser(arg0: Principal): Promise<Array<TaskResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksForUser(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksForUser(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markComplete(arg0: bigint): Promise<TaskResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.markComplete(arg0);
                return from_candid_TaskResponse_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markComplete(arg0);
            return from_candid_TaskResponse_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectTask(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTask(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleUserAccountStatus(arg0: Principal, arg1: AccountStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleUserAccountStatus(arg0, to_candid_AccountStatus_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleUserAccountStatus(arg0, to_candid_AccountStatus_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadProof(arg0: bigint, arg1: ExternalBlob): Promise<TaskResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProof(arg0, await to_candid_ExternalBlob_n53(this._uploadFile, this._downloadFile, arg1));
                return from_candid_TaskResponse_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProof(arg0, await to_candid_ExternalBlob_n53(this._uploadFile, this._downloadFile, arg1));
            return from_candid_TaskResponse_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AccountStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountStatus): AccountStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Department_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Department): Department {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FinalStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinalStatus): FinalStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPriority_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPriority): TaskPriority {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_TaskResponse_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskResponse): Promise<TaskResponse> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserStats_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStats): UserStats {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FinalStatus]): FinalStatus | null {
    return value.length === 0 ? null : from_candid_FinalStatus_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TaskStatus;
    title: string;
    proofFile: [] | [_ExternalBlob];
    assignedTo: Principal;
    completionTime: [] | [_Time];
    submissionTimestamp: [] | [_Time];
    finalStatus: [] | [_FinalStatus];
    rejectionReason: [] | [string];
    submittedAt: [] | [_Time];
    description: string;
    performancePoints: bigint;
    reviewComment: [] | [string];
    deadline: _Time;
    reviewedAt: [] | [_Time];
    approvalStatus: _ApprovalStatus;
    taskId: bigint;
    proofSubmittedBy: [] | [string];
    priority: _TaskPriority;
    proofSubmittedByEmail: [] | [string];
    department: _Department;
}): Promise<{
    status: TaskStatus;
    title: string;
    proofFile?: ExternalBlob;
    assignedTo: Principal;
    completionTime?: Time;
    submissionTimestamp?: Time;
    finalStatus?: FinalStatus;
    rejectionReason?: string;
    submittedAt?: Time;
    description: string;
    performancePoints: bigint;
    reviewComment?: string;
    deadline: Time;
    reviewedAt?: Time;
    approvalStatus: ApprovalStatus;
    taskId: bigint;
    proofSubmittedBy?: string;
    priority: TaskPriority;
    proofSubmittedByEmail?: string;
    department: Department;
}> {
    return {
        status: from_candid_TaskStatus_n13(_uploadFile, _downloadFile, value.status),
        title: value.title,
        proofFile: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.proofFile)),
        assignedTo: value.assignedTo,
        completionTime: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.completionTime)),
        submissionTimestamp: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.submissionTimestamp)),
        finalStatus: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.finalStatus)),
        rejectionReason: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.rejectionReason)),
        submittedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.submittedAt)),
        description: value.description,
        performancePoints: value.performancePoints,
        reviewComment: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.reviewComment)),
        deadline: value.deadline,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.reviewedAt)),
        approvalStatus: from_candid_ApprovalStatus_n22(_uploadFile, _downloadFile, value.approvalStatus),
        taskId: value.taskId,
        proofSubmittedBy: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.proofSubmittedBy)),
        priority: from_candid_TaskPriority_n24(_uploadFile, _downloadFile, value.priority),
        proofSubmittedByEmail: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.proofSubmittedByEmail)),
        department: from_candid_Department_n26(_uploadFile, _downloadFile, value.department)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalTasks: bigint;
    tasksCompleted: bigint;
    performancePoints: bigint;
    profile: _UserProfile;
}): {
    totalTasks: bigint;
    tasksCompleted: bigint;
    performancePoints: bigint;
    profile: UserProfile;
} {
    return {
        totalTasks: value.totalTasks,
        tasksCompleted: value.tasksCompleted,
        performancePoints: value.performancePoints,
        profile: from_candid_UserProfile_n38(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accountStatus: _AccountStatus;
    name: string;
    role: _UserRole;
    performancePoints: bigint;
    email: string;
    department: string;
}): {
    accountStatus: AccountStatus;
    name: string;
    role: UserRole;
    performancePoints: bigint;
    email: string;
    department: string;
} {
    return {
        accountStatus: from_candid_AccountStatus_n40(_uploadFile, _downloadFile, value.accountStatus),
        name: value.name,
        role: from_candid_UserRole_n42(_uploadFile, _downloadFile, value.role),
        performancePoints: value.performancePoints,
        email: value.email,
        department: value.department
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    blue: null;
} | {
    green: null;
} | {
    yellow: null;
}): TaskStatus {
    return "red" in value ? TaskStatus.red : "blue" in value ? TaskStatus.blue : "green" in value ? TaskStatus.green : "yellow" in value ? TaskStatus.yellow : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingReview: null;
} | {
    approved: null;
} | {
    rejected: null;
}): FinalStatus {
    return "pendingReview" in value ? FinalStatus.pendingReview : "approved" in value ? FinalStatus.approved : "rejected" in value ? FinalStatus.rejected : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingReview: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pendingReview" in value ? ApprovalStatus.pendingReview : "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): TaskPriority {
    return "low" in value ? TaskPriority.low : "high" in value ? TaskPriority.high : "medium" in value ? TaskPriority.medium : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    construction: null;
} | {
    marketing: null;
} | {
    accounts: null;
} | {
    travelDesk: null;
} | {
    apartments: null;
}): Department {
    return "construction" in value ? Department.construction : "marketing" in value ? Department.marketing : "accounts" in value ? Department.accounts : "travelDesk" in value ? Department.travelDesk : "apartments" in value ? Department.apartments : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): AccountStatus {
    return "active" in value ? AccountStatus.active : "inactive" in value ? AccountStatus.inactive : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    admin: null;
} | {
    employee: null;
}): UserRole {
    return "manager" in value ? UserRole.manager : "admin" in value ? UserRole.admin : "employee" in value ? UserRole.employee : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskResponse>): Promise<Array<TaskResponse>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TaskResponse_n11(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserStats>): Array<UserStats> {
    return value.map((x)=>from_candid_UserStats_n36(_uploadFile, _downloadFile, x));
}
function to_candid_AccountStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountStatus): _AccountStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_Department_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): _Department {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FinalStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinalStatus): _FinalStatus {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_TaskPriority_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): _TaskPriority {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accountStatus: AccountStatus;
    name: string;
    role: UserRole;
    performancePoints: bigint;
    email: string;
    department: string;
}): {
    accountStatus: _AccountStatus;
    name: string;
    role: _UserRole;
    performancePoints: bigint;
    email: string;
    department: string;
} {
    return {
        accountStatus: to_candid_AccountStatus_n49(_uploadFile, _downloadFile, value.accountStatus),
        name: value.name,
        role: to_candid_UserRole_n51(_uploadFile, _downloadFile, value.role),
        performancePoints: value.performancePoints,
        email: value.email,
        department: value.department
    };
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): {
    construction: null;
} | {
    marketing: null;
} | {
    accounts: null;
} | {
    travelDesk: null;
} | {
    apartments: null;
} {
    return value == Department.construction ? {
        construction: null
    } : value == Department.marketing ? {
        marketing: null
    } : value == Department.accounts ? {
        accounts: null
    } : value == Department.travelDesk ? {
        travelDesk: null
    } : value == Department.apartments ? {
        apartments: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == TaskPriority.low ? {
        low: null
    } : value == TaskPriority.high ? {
        high: null
    } : value == TaskPriority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == AccountStatus.active ? {
        active: null
    } : value == AccountStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    manager: null;
} | {
    admin: null;
} | {
    employee: null;
} {
    return value == UserRole.manager ? {
        manager: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.employee ? {
        employee: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinalStatus): {
    pendingReview: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == FinalStatus.pendingReview ? {
        pendingReview: null
    } : value == FinalStatus.approved ? {
        approved: null
    } : value == FinalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
